-
  name: "Update packages"
  hosts: all
  become: true
  tasks:
    - name: apt-get update
      apt:
        update_cache: yes
      register: apt_update_output

    - name: Debug output
      debug:
        msg: "{{ apt_update_output.stdout_lines }}"
       
