-
  name: "Update packages"
  hosts: all
  become: true
  tasks:
    - name: apt-get update
      apt:
        update_cache: yes

    - name: unattended-upgrade
      command: unattended-upgrade -v --dry-run 
      register: unattended_upgrade
 
    - name: Debug registered var
      debug: var=unattended_upgrade.stdout_lines
