-
  name: "Update packages"
  hosts: all
  become: true
  tasks:
    - name: apt-get update
      apt:
        update_cache: yes
      register: apt_get_update_result

    - name: Debug registered var
      debug: var=apt_get_update_result.stdout_lines
