-
  name: "Update packages"
  hosts: all
  become: true
  tasks:
    - name: apt-get update
      apt:
        update_cache: yes
      register: output

    - name: Debug output
      debug:
        var: apt_update.stdout_lines
       
